# -*- coding: utf-8 -*-
"""e

Automatically generated by Colab.


"""

import pandas as pd

import matplotlib.pyplot as plot
import seaborn as sns
import numpy as np
from scipy.stats import norm

from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, mean_absolute_error

alldata = pd.read_csv('housesales.csv')

"""# DATA EXPLORATION

Check how much data we have

Is the dataset large enough to train a model?
"""

print(alldata.shape)
"""Conclusion: There are 1460 rows, which at first sight looks like a good enough to train an initial model.
The data is not extensive enough for production use but would help establish a good baseline.
We also see that there are 80 input features that we can potentially use to predict our target variable.
Review the target attribute: SalePrice

Before we look at the input features, let's have a close look at our Target attribute: SalePrice.

First, let's display some values.
"""

print(alldata['SalePrice'].head())

"""Let's check if there are any empty values, min and max"""

print(alldata['SalePrice'].isnull().sum())
minPrice = alldata['SalePrice'].min()
maxPrice = alldata['SalePrice'].max()
print('Min Sales Price (%d) - Max Sales Price (%d)' % (minPrice,maxPrice))

"""Which columns will we select as input features for our model?
Let's start by listing all the columns.
"""

print(alldata.columns)

"""As we can see there are too many, maybe more usefull will be to separate them and see only the numeric and the categorical one.
Let's get a list of all numeric features first.
"""

print(alldata.select_dtypes(include=np.number).columns.tolist())
#print(alldata.select_dtypes(include=[np.number]))
print(alldata.select_dtypes(exclude=np.number).columns.tolist())
#print(alldata.select_dtypes(exclude=[np.number]))

"""Let's test our theories that these input features are correlated with Sale Price.
We'll start with the numerical variables first: GrLivArea, TotalBsmtSF, OverallQual and YearBuilt.
Because all of these are numerical continuous attributes, we can use scatter plots here.

GrLivArea: Above grade (ground) living area square feet
"""

plot.scatter(alldata.GrLivArea, alldata.SalePrice)
plot.xlabel("GrLivArea")
plot.ylabel("SalePrice")
plot.show()

"""TotalBsmtSF: Total square feet of basement area"""

plot.scatter(alldata.TotalBsmtSF, alldata.SalePrice)
plot.xlabel("TotalBsmtSF")
plot.ylabel("SalePrice")
plot.show()

"""OverallQual: Rates the overall material and finish of the house"""

plot.scatter(alldata.OverallQual, alldata.SalePrice)
plot.xlabel("OverallQual")
plot.ylabel("SalePrice")
plot.show()

"""YearBuilt: Original construction date"""

plot.scatter(alldata.YearBuilt, alldata.SalePrice)
plot.xlabel("YearBuilt")
plot.ylabel("SalePrice")
plot.show()


"""Do we have Missing Data?
Many machine learning models are unable to handle missing data. We have to find out how much data is missing.
At the moment of replacing missing data, we should first find out whether that would cause some kind of distortion in the data
and have a negative effect on model quality. Therefore, we have to see if the missing data follows certain patterns.
Check how many Empty values each column has, and compute the percentage of the total number of rows.
"""

total = alldata.isnull().sum().sort_values(ascending=False)
percent = (alldata.isnull().sum()/alldata.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
print(missing_data.head(20))

"""It seems sensible to assume that most houses don't have pools and therefore missing values simply mean "No Pool".
Therefore we make a note to replace those missing values with "NA". Similarly, we make a note to replace the missing values for MiscFeature, Alley, Fence
and FireplaceQu with "NA".
The next attribute with many hidden values is LotFrontage, 
which means "Linear feet of street connected to property".
This is a continuous measure, and we choose that we will replace missing values by with the mean of the existing values.

Conclusion: There are a lot of attributes with missing values. This is especially the case for attributes PoolQC, MiscFeature, Alley, Fence and FireplaceQu


#next ->
Check the distribution of the Target variable


It's important that the target variable follows Normal Probability distribution.

A target variable that is not well-distributed (e.g., heavily skewed towards small or large values) can cause the model to "focus" only on certain types of values.
If the distribution is normal (bell-shaped), the model learns more easily to predict all values correctly, not just the extremes.
When the target variable has a normal distribution, it is also easier to understand how each feature influences the final prediction.

If it does not, this will negatively impact the model's performance.
We can check for this using a histogram, and including a normal probability plot. The Seaborn library does this for us.
"""

sns.distplot(tuple(alldata['SalePrice']), fit=norm);
plot.show()

"""Conclusion: This deviates from the Normal Distribution. You see that it is left skewed.
The regression algorithms that we will use later on has problems with such a distribution. We will have to address this problem.

# DATA PREPARATION

During Data Exploration, we have realized that several changes must be made to the dataset.
Data Preparation is a logical result of Data Exploration; we will now take action based on the insights that we gained earlier.

### Update missing values
In the previous topic (identifying Missing Values) we made the decision that:
    - We want to replace the missing values of PoolQC, MiscFeature, Alley, Fence and FireplaceQu with "NA".
    - We will replace missing values of LotFrontage with the mean of the existing values. Let's do this:
"""

alldata = alldata.fillna({"PoolQC": "NA"})
alldata = alldata.fillna({"MiscFeature": "NA"})
alldata = alldata.fillna({"Alley": "NA"})
alldata = alldata.fillna({"Fence": "NA"})
alldata = alldata.fillna({"FireplaceQu": "NA"})
meanlot = alldata['LotFrontage'].mean()
alldata = alldata.fillna({"LotFrontage": meanlot})
alldata = alldata.dropna()

print('Checking the missing values after fillna')
total = alldata.isnull().sum().sort_values(ascending=False)
percent = (alldata.isnull().sum()/alldata.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
print(missing_data.head(20))

"""### Handling Outliers
Do you remember that the scatter chart for GrLivArea showed several outliers? Let's remove these two outliers, by identifying the houses with the highest GrLivArea.
Show the IDs of the houses with the highest GrLivArea.
"""

alldata.sort_values(by = 'GrLivArea', ascending = False)[:2]

"""Now remove them and plot the chart again to check that the outliers have disappeared."""

alldata = alldata.drop(alldata[alldata['Id'] == 1299].index)
alldata = alldata.drop(alldata[alldata['Id'] == 524].index)
plot.scatter(alldata.GrLivArea, alldata.SalePrice)
plot.xlabel("GrLivArea")
plot.ylabel("SalePrice")
plot.show()

"""We could check for outliers in other attributes, but this is sufficient for our exercise.

### Handling the skewed distribution of the Target variable
Do you remember that the histogram of SalePrice showed a positive skew? We can solve this problem by converting the target variable.
We use a -log- transformation to make the variable fit normal distribution. When data has extremely large values (like 1,000,000) and small values (like 10), the range is too wide, and the distribution becomes skewed.
np.log compresses the large values more than the small ones, bringing them closer together. This "squeezes" the data and makes the distribution more balanced or closer to a normal (bell-shaped) curve. Let's make the log transformation and show the histogram again to check the result:
"""

y = np.log(alldata['SalePrice'])
sns.distplot(y, fit=norm)
plot.show()

"""Conclusion: Now the sales price follows a normal distribution. We will use the newly created y variable later to fit our model.

### Removing irrelevant features
In any case we will remove the ID column, which does not carry any predictive value.
We will also remove the attributes that showed very low correlation with SalePrice during Data Exploration.
Note that this is a fairly brute approach, but it is again sufficient for our exercise.
After the first model build, you could start adding back some of the features and observe if the model will generalize better.
"""

alldata.drop("Id", axis = 1, inplace = True)
alldata.drop("BsmtFullBath", axis = 1, inplace = True)
alldata.drop("BsmtUnfSF", axis = 1, inplace = True)
alldata.drop("ScreenPorch", axis = 1, inplace = True)
alldata.drop("MoSold", axis = 1, inplace = True)
alldata.drop("3SsnPorch", axis = 1, inplace = True)
alldata.drop("PoolArea", axis = 1, inplace = True)
alldata.drop("MSSubClass", axis = 1, inplace = True)
alldata.drop("YrSold", axis = 1, inplace = True)
alldata.drop("BsmtFinSF2", axis = 1, inplace = True)
alldata.drop("MiscVal", axis = 1, inplace = True)
alldata.drop("LowQualFinSF", axis = 1, inplace = True)
alldata.drop("OverallCond", axis = 1, inplace = True)
alldata.drop("KitchenAbvGr", axis = 1, inplace = True)
alldata.drop("EnclosedPorch", axis = 1, inplace = True)

"""### Separating Target and Input Features

Scikit Learn expects that we deliver the data for training in two parts:

    A dataset with a single column, the target, in this case SalePrice. We did this already earlier by taking the log of the SalePrice and storing it in "y" variable.
    A dataset with all the input columns, in this case all columns apart from SalePrice. We will place this in variable "X".

Get all the data with the exception of the SalePrice:
"""

X = alldata.drop(['SalePrice'], axis=1)

"""### Convert categorical values to numbers

Most ML algorithms can only work with numbers. Therefore we should convert categories to numbers first.

For all attributes we will assume that they are Nominal (as opposed to Ordinal), meaning that there's no order/sequence in the values that it can take.
The go-to method to encode Nominal categorical values is Onehot Encoding.
This will convert each separate value of a category into its own column that can take a value of 1 or 0. The Pandas get_dummies function does OneHot encoding.'''

"""

X = pd.get_dummies(X)

"""Conclusion: For example, see the SaleType column that has been converted into SaleType_ConLw, SaleType_New, et cetera. The dataset now only has numerical values.'''"""

print(X.columns)



"""# USING ML FOR PRICE PREDICTION

### Split Train and Test data so we can validate the model later

After building the model, we will want to test its performance against new data.
It's important that this data has not been seen before during the model training.
To achieve this we have to reserve part of our dataset for testing, which will be removed from the training phase.

We'll reserve 20% of the total dataset for testing. The random_state variable is for initializng the randomizer.
By hardcoding it here we make sure that we select the same records everytime that we run the script.
"""

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=63, test_size=.20)

"""Now we have 4 variables:
    X_train: The input features of the training dataset.
    X_test: The input features of the test dataset.
    y_train: The target of the training dataset.
    y_train: The target of the test dataset.

### Building the Linear Regression (LR) model
We will build a simple Linear Regression model. We will use the Scikit-Learn library for this.

### Train the LR model on the X_train
Now we're ready to build the model (on the training data only). Building the model is also called "fitting".
"""

lr = linear_model.LinearRegression()
model = lr.fit(X_train, y_train)
y_predicted = model.predict(X_train)

"""### Verifying the accuracy of LR the model on the train set
To verify the quality of the predictions, let's first use an intuitive visual approach, which works well for linear regression models. For this we will display in one plot:
    The actual SalePrice (according to the original data in the Train dataset)
    The predicted SalePrice (the value according to our model)
We're plotting this as a scatter.
"""

plot.scatter(y_predicted, y_train)
plot.xlabel('Predicted Sale Price')
plot.ylabel('Actual Sale Price')
plot.title('Comparing Predicted and Actual Sale Prices')
plot.plot(range(11, 15), range(11, 15), color="red")
plot.show()

"""How can we express the accuracy of the model in a more mathematical way? For that we use a quality metric, in this case we could use RMSE.
In essence RMSE measures the distance between the predictions and the actual values.
 A lower value for RMSE means a higher accuracy.
RMSE by itself is not easy to interpret, but it can be used to compare different versions of a model, to see whether a change you've made has resulted in an improvement.
Scikit-Learn has a function to calculate RMSE.
"""

print('RMSE LR Train set: ', mean_squared_error(y_train, y_predicted))

"""### Test the LR model on the X_test

We will use the Test dataset to apply the predictions
"""

y_predicted = model.predict(X_test)

"""### Verifying the accuracy of the LR model on the test set
We're plotting this as a scatter y_predicted vs. y_test.
"""

plot.scatter(y_predicted, y_test)
plot.xlabel('Predicted Sale Price')
plot.ylabel('Actual Sale Price')
plot.title('Comparing Predicted and Actual Sale Prices')
plot.plot(range(11, 15), range(11, 15), color="red")
plot.show()

"""Conclusion: In ideal circumstances we'd like to see the predictions aling perfectly on the straight line.
This would mean that Predicted and Actual Sale Prices are the same which practically is usually impossible or it is a sign for model overfitting.
RMSE stands for Root Mean Squared Error, and it tells us the average difference between the predicted values (ypred) and the actual values (y true) in the same units as the target variable. A smaller RMSE indicates that the model's predictions are closer to the actual values.
A measurable approach to verification - RMSE on the Test set:
"""


print('MSE LR test set: ', mean_squared_error(y_test, y_predicted))

"""
MSE – Mean Squared Error
Media pătratelor diferențelor dintre valori reale și prezise.
"""
mse = mean_squared_error(y_test, y_predicted)
print(f"MSE: {mse:.4f}")
"""
RMSE – Root Mean Squared Error
Rădăcina pătrată a MSE. Este în aceleași unități ca ținta (SalePrice în log).
"""

rmse = np.sqrt(mse)
print(f"RMSE: {rmse:.4f}")
"""
 MAE – Mean Absolute Error
Media valorilor absolute ale erorilor.
"""

mae = mean_absolute_error(y_test, y_predicted)
print(f"MAE: {mae:.4f}")


"""
R² – Coeficientul de determinare
Procentul din variația lui y explicat de model"""


from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_predicted)
print(f"R² (R squared): {r2:.4f}")
"""
Valori posibile: (-∞, 1]

1 = predicție perfectă, 0
"""


"""### Apply the model for new predictions
Single house SalesPrice prediction
Let's use now the model and try to predict the SalesPrice for a house.
From the given test set we would get the data from one house,
to see how this works and to have this as reference example later if you want to deploy the model and use it as REST Services for example.
"""

single_predicted = model.predict(X_test[2:3])
print(single_predicted)

"""You would notice that the price is strange, it shows a number that doesn't seem to be a normal house Sales Price.
If you remember we scaled the SalePrice by using np.log(SalePrice) to get the prices in smaller range and help the algorithm generalize and learn better.
To get the real price now we need to revert back this scale. To do so we have to use np.exp(PredictedSalePrice), example:
"""

print('Single House price prediction with LR:', np.exp(single_predicted))



